platform: linux

image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.6.1-jdk-14}

inputs:
  - name: pool-monitor

outputs:
  - name: build-output

caches:
  - path: maven

run:
  path: "pool-monitor/ci/tasks/build.sh"