platform: linux

image_resource:
  type: docker-image
  source: {repository: gcr.io/fe-mwright/cruiseline/tools, tag: latest}

inputs:
  - name: venues

params:
  KUBECONFIG: 
  CONTEXT: 

run:
  path: "venues/ci/tasks/deploy-to-k8s.sh"