platform: linux

image_resource:
  type: docker-image
  source: 
    repository: mwrightregistry.azurecr.io/tools
    tag: latest
    username: ((REGISTRY_USERNAME))
    password: ((REGISTRY_PASSWORD))

inputs:
  - name: venues

params:
  KUBECONFIG_CONTENTS: 
  CONTEXT: 

run:
  path: "venues/ci/tasks/kapp.sh"