platform: linux

image_resource:
  type: docker-image
  source: {repository: harbor.sys.pks.wrightcode.io/tools/clis, tag: latest}

params:
  GOOGLE_TOKEN:
  KUBE_CONFIG:
  DOCKER_IMAGE:
  DOCKER_USERNAME:
  DOCKER_PASSWORD:
  DOCKER_REGISTRY:

inputs:
  - name: pool-monitor

outputs:
  - name: build-output

run:
  path: "pool-monitor/ci/tasks/pack.sh"