platform: linux

image_resource:
  type: docker-image
  source: 
    repository: harbor.sys.pks.wrightcode.io/tools/clis
    tag: latest
    username: ((REGISTRY_USERNAME))
    password: ((REGISTRY_PASSWORD))

inputs:
  - name: pool-monitor

params:
  KUBECONFIG: 
  CONTEXT: 
  SNYK_TOKEN:

run:
  path: "pool-monitor/ci/tasks/snyk.sh"