resources:
  - name: venue
    type: git
    check_every: 10s
    source:
      uri: https://github.com/mwright-pivotal/cruiseline-venues.git
      branch: master

  - name: resource-deploy-web-app
    type: cf
    source:
      api: ((cf-api))
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-space))
      skip_cert_check: false

jobs:
  - name: build
    public: true
    plan:
      - get: venue
        trigger: true
      - task: Build project
        file: venue/ci/tasks/build.yml
      - put: resource-deploy-web-app
        params:
          manifest: build-output/manifest.yml
          environment_variables:
            key: SPRING_DATA_USERNAME
            key2: mwright
