name: venue
version: 0.0.1
appVersion: 1.0.0
description: Venue Service
icon: https://avatars1.githubusercontent.com/u/7809479
keywords:
- app
- venue
- rccl
home: https://appurl/orders/
sources:
- https://github.com/rrajaram-pivotal/pks-kafka-work/
maintainers:
- name: Mayuresh Krishna
  email: makrishna@pivotal.io
engine: gotpl
