apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pool-monitor
  labels:
    app.kubernetes.io/part-of: pool-monitor
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/java-build: maven
spec:
  source:
    git:
      url: https://github.com/mwright-pivotal/pool-monitoring
      ref:
        branch: master
  serviceClaims:
    - name: edge-pos-psql-server
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: edge-pos-psql-server

